<?php
$excel_headers_old = array(
    'IP' => 'ip',
    'Submission ID' => 'submission_id',
    'Submission Date' => 'submission_date',
    'First Name' => 'first_name',
    'Last Name' => 'last_name',
    'Country of Residence' => 'country_of_residence',
    'SNM  Branch' => 'snm_branch',
    'E-mail' => 'email',
    'Mobile Phone Number' => 'phone',
    'Age (Guideline 7-30 yrs)' => 'age',
    'Gender' => 'gender',
    'T-Shirt Size' => 'tshirt_size',
    'Do you want to register Additional Guests?' => 'additional_guests',
    'Guest Name(s) and General Information >> Guest 1 >> First Name' => 'first_name',
    'Guest Name(s) and General Information >> Guest 1 >> Last Name' => 'last_name',
    'Guest Name(s) and General Information >> Guest 1 >> Gender <br>(M/F)' => 'gender',
    'Guest Name(s) and General Information >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important...' => 'age',
    'Guest Name(s) and General Information >> Guest 1 >> Email <br>(leave blank <br>if no email)<br>' => 'email',
    'Guest Name(s) and General Information >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'phone',
    'Guest Name(s) and General Information >> Guest 2 >> First Name' => 'first_name',
    'Guest Name(s) and General Information >> Guest 2 >> Last Name' => 'last_name',
    'Guest Name(s) and General Information >> Guest 2 >> Gender <br>(M/F)' => 'gender',
    'Guest Name(s) and General Information >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important...' => 'age',
    'Guest Name(s) and General Information >> Guest 2 >> Email <br>(leave blank <br>if no email)<br>' => 'email',
    'Guest Name(s) and General Information >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'phone',
    'Guest Name(s) and General Information >> Guest 3 >> First Name' => 'first_name',
    'Guest Name(s) and General Information >> Guest 3 >> Last Name' => 'last_name',
    'Guest Name(s) and General Information >> Guest 3 >> Gender <br>(M/F)' => 'gender',
    'Guest Name(s) and General Information >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important...' => 'age',
    'Guest Name(s) and General Information >> Guest 3 >> Email <br>(leave blank <br>if no email)<br>' => 'email',
    'Guest Name(s) and General Information >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'phone',
    'Guest Name(s) and General Information >> Guest 4 >> First Name' => 'first_name',
    'Guest Name(s) and General Information >> Guest 4 >> Last Name' => 'last_name',
    'Guest Name(s) and General Information >> Guest 4 >> Gender <br>(M/F)' => 'gender',
    'Guest Name(s) and General Information >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important...' => 'age',
    'Guest Name(s) and General Information >> Guest 4 >> Email <br>(leave blank <br>if no email)<br>' => 'email',
    'Guest Name(s) and General Information >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'phone',
    'Guest Name(s) and General Information >> Guest 5 >> First Name' => 'first_name',
    'Guest Name(s) and General Information >> Guest 5 >> Last Name' => 'last_name',
    'Guest Name(s) and General Information >> Guest 5 >> Gender <br>(M/F)' => 'gender',
    'Guest Name(s) and General Information >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important...' => 'age',
    'Guest Name(s) and General Information >> Guest 5 >> Email <br>(leave blank <br>if no email)<br>' => 'email',
    'Guest Name(s) and General Information >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'phone',
    'Guest Name(s) and General Information >> Guest 6 >> First Name' => 'first_name',
    'Guest Name(s) and General Information >> Guest 6 >> Last Name' => 'last_name',
    'Guest Name(s) and General Information >> Guest 6 >> Gender <br>(M/F)' => 'gender',
    'Guest Name(s) and General Information >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important...' => 'age',
    'Guest Name(s) and General Information >> Guest 6 >> Email <br>(leave blank <br>if no email)<br>' => 'email',
    'Guest Name(s) and General Information >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'phone',
    'Guest Name(s) and General Information >> Guest 7 >> First Name' => 'first_name',
    'Guest Name(s) and General Information >> Guest 7 >> Last Name' => 'last_name',
    'Guest Name(s) and General Information >> Guest 7 >> Gender <br>(M/F)' => 'gender',
    'Guest Name(s) and General Information >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important...' => 'age',
    'Guest Name(s) and General Information >> Guest 7 >> Email <br>(leave blank <br>if no email)<br>' => 'email',
    'Guest Name(s) and General Information >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'phone',
    'Guest Name(s) and General Information >> Guest 8 >> First Name' => 'first_name',
    'Guest Name(s) and General Information >> Guest 8 >> Last Name' => 'last_name',
    'Guest Name(s) and General Information >> Guest 8 >> Gender <br>(M/F)' => 'gender',
    'Guest Name(s) and General Information >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important...' => 'age',
    'Guest Name(s) and General Information >> Guest 8 >> Email <br>(leave blank <br>if no email)<br>' => 'email',
    'Guest Name(s) and General Information >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'phone',
    'Guest Name(s) and General Information >> Guest 9 >> First Name' => 'first_name',
    'Guest Name(s) and General Information >> Guest 9 >> Last Name' => 'last_name',
    'Guest Name(s) and General Information >> Guest 9 >> Gender <br>(M/F)' => 'gender',
    'Guest Name(s) and General Information >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important...' => 'age',
    'Guest Name(s) and General Information >> Guest 9 >> Email <br>(leave blank <br>if no email)<br>' => 'email',
    'Guest Name(s) and General Information >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'phone',
    'Guest T-Shirt Size >> Guest 1 >> Guest <br>T-shirt Size' => 'tshirt_size',
    'Guest T-Shirt Size >> Guest 2 >> Guest <br>T-shirt Size' => 'tshirt_size',
    'Guest T-Shirt Size >> Guest 3 >> Guest <br>T-shirt Size' => 'tshirt_size',
    'Guest T-Shirt Size >> Guest 4 >> Guest <br>T-shirt Size' => 'tshirt_size',
    'Guest T-Shirt Size >> Guest 5 >> Guest <br>T-shirt Size' => 'tshirt_size',
    'Guest T-Shirt Size >> Guest 6 >> Guest <br>T-shirt Size' => 'tshirt_size',
    'Guest T-Shirt Size >> Guest 7 >> Guest <br>T-shirt Size' => 'tshirt_size',
    'Guest T-Shirt Size >> Guest 8 >> Guest <br>T-shirt Size' => 'tshirt_size',
    'Guest T-Shirt Size >> Guest 9 >> Guest <br>T-shirt Size' => 'tshirt_size',
    'TRAVEL ARRANGEMENTS: Have you made travel arrangements / bookings to/from Houston?  (NOTE: all fields may not be visible if registering via mobile phone)' => 'travel_arrangements',
    'Is everyone you are registering traveling on the same itinerary (i.e. are you all traveling together)?' => 'same_guest_itinerary',
    'Date/Time of Arrival into Houston (please enter in time as well)' => 'arrival_time',
    'Arrival Flight Details' => 'arrival_flight',
    'Arrival Flight Number' => 'arrival_flight_number',
    'Arrival Airport?' => 'arrival_airport',
    'Do you require transportation FROM the Airport?' => 'require_transportation_from',
    'Date/Time of Departure from Houston (please enter in time as well)' => 'departure_time',
    'Departure Flight Details' => 'departure_flight',
    'Departure Flight Number' => 'departure_flight_number',
    'Departure Airport?' => 'departure_airport',
    'Do you (or everyone in your group) require transportation TO the Airport?' => 'require_transportation_to',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'arrival_date_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'arrival_time_member',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important...' => 'arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> Transportation required FROM the airport (Y/N)?' => 'require_transportation_arrival',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'departure_date_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'departure_time_member',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important...' => 'departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> Transportation required TO the airport (Y/N)?' => 'require_transportation_departure',
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'arrival_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'arrival_time_member',
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'departure_date_member',
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'departure_time_member',
    'LODGING/LIVING ARRANGEMENTS: Have you made hotel/lodging arrangements?' => 'hotel_arrangements',
    'Are all the people you are registering staying in the same hotel/accommodation?' => 'accomodation_same',
    'At which Hotel / Accommodations are you staying (please specify name and address)?' => 'hotel_detail_same',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> You (Primary Registrant) >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 1 >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 2 >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 3 >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 4 >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 5 >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 6 >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 7 >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 8 >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 9 >> Hotel/Accommodation <br>(Name & Address)' => 'hotel_detail',
    'GROUND TRANSPORTATION: How do you intend to get to/from the hotels and venues/events?' => 'transportation_option',
    'Individual Ground Transportation Details >> You (Primary Registrant) >> Transportation required from SNM Partner hotels <br>to/from ...' => 'ground_transportation',
    'Individual Ground Transportation Details >> Guest 1 >> Transportation required from SNM Partner hotels <br>to/from ...' => 'ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ...' => 'ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 2' => 'ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 3' => 'ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 4' => 'ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 5' => 'ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 6' => 'ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 7' => 'ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 8' => 'ground_transportation',
    'OPTIONAL VOLUNTEER: If you or members of your group are part of the Sewadal or interested in Volunteering for this event, kindly select the skills/experience you already have, or have helped with previously (check all that apply). Please also take a moment to update your profile at http://nirankari.org/intranet/community so we know your skills for future sewa opportunities' => 'volunteer',
    'Medical Field: Area of Expertise' => 'medical',
    'State of License' => 'medical_state_of_license',
    'Do you want to submit a Poster?' => 'submit_poster',
    'Please enter a brief description about the poster(s).' => 'poster_description',
    'Are you bringing any medications/supplies/equipment?' => 'bringing_medical_equipment',
    'What type of medications/supplies/equipment?' => 'what_medical_equipment',
    'Legal Acknowledgement' => 'legal',
    'Unique ID (please note down this number)' => 'unique_id'
);
//
//
//foreach($excel_headers_old as $key=> $column){
//    $columns[$column] = $column;
//}
//
//echo "<br>";
//echo $query = "CREATE TABLE registrations ( <br>";
//foreach($columns as $column){
//    echo "$column varchar(100), <br>";
//}
//
//
//echo "<pre>";
//print_r($columns);
?>