<?php

$excel_headers = array(
    'IP' => array('ip', 'varchar(30)'),
    'Submission ID' => array('submission_id', 'varchar(30)'),
    'Submission Date' => array('submission_date', 'varchar(30)'),
    'First Name' => array('first_name', 'varchar(30)'),
    'Last Name' => array('last_name', 'varchar(30)'),
    'Country of Residence' => array('country_of_residence', 'varchar(30)'),
    'SNM  Branch' => array('snm_branch', 'varchar(30)'),
    'E-mail' => array('email', 'varchar(30)'),
    'Mobile Phone Number' => array('phone', 'varchar(30)'),
    'Age (Guideline 7-30 yrs)' => array('age', 'varchar(30)'),
    'Gender' => array('gender', 'varchar(30)'),
    'T-Shirt Size' => array('tshirt_size', 'varchar(30)'),
    'Do you want to register Additional Guests?' => array('additional_guests', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 1 >> First Name' => array('guest1_first_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 1 >> Last Name' => array('guest1_last_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 1 >> Gender <br>(M/F)' => array('guest1_gender', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest1_age', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 1 >> Email <br>(leave blank <br>if no email)<br>' => array('guest1_email', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important... 2' => array('guest1_phone', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 2 >> First Name' => array('guest2_first_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 2 >> Last Name' => array('guest2_last_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 2 >> Gender <br>(M/F)' => array('guest2_gender', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest2_age', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 2 >> Email <br>(leave blank <br>if no email)<br>' => array('guest2_email', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important... 2' => array('guest2_phone', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 3 >> First Name' => array('guest3_first_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 3 >> Last Name' => array('guest3_last_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 3 >> Gender <br>(M/F)' => array('guest3_gender', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest3_age', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 3 >> Email <br>(leave blank <br>if no email)<br>' => array('guest3_email', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important... 2' => array('guest3_phone', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 4 >> First Name' => array('guest4_first_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 4 >> Last Name' => array('guest4_last_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 4 >> Gender <br>(M/F)' => array('guest4_gender', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest4_age', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 4 >> Email <br>(leave blank <br>if no email)<br>' => array('guest4_email', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important... 2' => array('guest4_phone', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 5 >> First Name' => array('guest5_first_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 5 >> Last Name' => array('guest5_last_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 5 >> Gender <br>(M/F)' => array('guest5_gender', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest5_age', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 5 >> Email <br>(leave blank <br>if no email)<br>' => array('guest5_email', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important... 2' => array('guest5_phone', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 6 >> First Name' => array('guest6_first_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 6 >> Last Name' => array('guest6_last_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 6 >> Gender <br>(M/F)' => array('guest6_gender', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest6_age', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 6 >> Email <br>(leave blank <br>if no email)<br>' => array('guest6_email', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important... 2' => array('guest6_phone', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 7 >> First Name' => array('guest7_first_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 7 >> Last Name' => array('guest7_last_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 7 >> Gender <br>(M/F)' => array('guest7_gender', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest7_age', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 7 >> Email <br>(leave blank <br>if no email)<br>' => array('guest7_email', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important... 2' => array('guest7_phone', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 8 >> First Name' => array('guest8_first_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 8 >> Last Name' => array('guest8_last_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 8 >> Gender <br>(M/F)' => array('guest8_gender', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest8_age', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 8 >> Email <br>(leave blank <br>if no email)<br>' => array('guest8_email', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important... 2' => array('guest8_phone', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 9 >> First Name' => array('guest9_first_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 9 >> Last Name' => array('guest9_last_name', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 9 >> Gender <br>(M/F)' => array('guest9_gender', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest9_age', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 9 >> Email <br>(leave blank <br>if no email)<br>' => array('guest9_email', 'varchar(30)'),
    'Guest Name(s) and General Information >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important... 2' => array('guest9_phone', 'varchar(30)'),
    'Guest T-Shirt Size >> Guest 1 >> Guest <br>T-shirt Size' => array('guest1_tshirt_size', 'varchar(30)'),
    'Guest T-Shirt Size >> Guest 2 >> Guest <br>T-shirt Size' => array('guest2_tshirt_size', 'varchar(30)'),
    'Guest T-Shirt Size >> Guest 3 >> Guest <br>T-shirt Size' => array('guest3_tshirt_size', 'varchar(30)'),
    'Guest T-Shirt Size >> Guest 4 >> Guest <br>T-shirt Size' => array('guest4_tshirt_size', 'varchar(30)'),
    'Guest T-Shirt Size >> Guest 5 >> Guest <br>T-shirt Size' => array('guest5_tshirt_size', 'varchar(30)'),
    'Guest T-Shirt Size >> Guest 6 >> Guest <br>T-shirt Size' => array('guest6_tshirt_size', 'varchar(30)'),
    'Guest T-Shirt Size >> Guest 7 >> Guest <br>T-shirt Size' => array('guest7_tshirt_size', 'varchar(30)'),
    'Guest T-Shirt Size >> Guest 8 >> Guest <br>T-shirt Size' => array('guest8_tshirt_size', 'varchar(30)'),
    'Guest T-Shirt Size >> Guest 9 >> Guest <br>T-shirt Size' => array('guest9_tshirt_size', 'varchar(30)'),
    'TRAVEL ARRANGEMENTS: Have you made travel arrangements / bookings to/from Houston?  (NOTE: all fields may not be visible if registering via mobile phone)' => array('travel_arrangements', 'varchar(30)'),
    'Is everyone you are registering traveling on the same itinerary (i.e. are you all traveling together)?' => array('same_guest_itinerary', 'varchar(30)'),
    'Date/Time of Arrival into Houston (please enter in time as well)' => array('arrival_time', 'varchar(30)'),
    'Arrival Flight Details' => array('arrival_flight', 'varchar(30)'),
    'Arrival Flight Number' => array('arrival_flight_number', 'varchar(30)'),
    'Arrival Airport?' => array('arrival_airport', 'varchar(30)'),
    'Do you require transportation FROM the Airport?' => array('require_transportation', 'varchar(30)'),
    'Date/Time of Departure from Houston (please enter in time as well)' => array('departure_time', 'varchar(30)'),
    'Departure Flight Details' => array('departure_flight', 'varchar(30)'),
    'Departure Flight Number' => array('departure_flight_number', 'varchar(30)'),
    'Departure Airport?' => array('departure_airport', 'varchar(30)'),
    'Do you (or everyone in your group) require transportation TO the Airport?' => array('require_transportation_all', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('primary_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('primary_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('primary_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> <span style="font-size: 11.004px; display: inline !important...' => array('primary_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('primary_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> Transportation required FROM the airport (Y/N)?' => array('primary_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('guest1_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('guest1_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('guest1_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest1_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('guest1_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> Transportation required FROM the airport (Y/N)?' => array('guest1_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('guest2_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('guest2_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('guest2_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest2_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('guest2_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> Transportation required FROM the airport (Y/N)?' => array('guest2_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('guest3_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('guest3_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('guest3_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest3_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('guest3_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> Transportation required FROM the airport (Y/N)?' => array('guest3_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('guest4_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('guest4_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('guest4_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest4_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('guest4_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> Transportation required FROM the airport (Y/N)?' => array('guest4_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('guest5_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('guest5_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('guest5_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest5_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('guest5_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> Transportation required FROM the airport (Y/N)?' => array('guest5_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('guest6_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('guest6_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('guest6_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest6_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('guest6_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> Transportation required FROM the airport (Y/N)?' => array('guest6_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('guest7_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('guest7_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('guest7_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest7_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('guest7_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> Transportation required FROM the airport (Y/N)?' => array('guest7_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('guest8_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('guest8_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('guest8_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest8_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('guest8_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> Transportation required FROM the airport (Y/N)?' => array('guest8_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> Arrival Date<br>(yyyy-mm-dd)<br>' => array('guest9_arrival_date', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => array('guest9_arrival_time', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => array('guest9_arrival_flight', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest9_arrival_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => array('guest9_arrival_airport', 'varchar(30)'),
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> Transportation required FROM the airport (Y/N)?' => array('guest9_require_transportation_arrival', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> Departure Date<br>(yyyy-mm-dd)<br>' => array('primary_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('primary_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('primary_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> <span style="font-size: 11.004px; display: inline !important...' => array('primary_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('primary_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> Transportation required TO the airport (Y/N)?' => array('primary_require_transportation_departure', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> Departure Date<br>(yyyy-mm-dd)<br>' => array('guest1_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('guest1_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('guest1_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest1_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('guest1_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> Transportation required TO the airport (Y/N)?' => array('guest1_require_transportation_departure', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> Departure Date<br>(yyyy-mm-dd)<br>' => array('guest2_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('guest2_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('guest2_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest2_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('guest2_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> Transportation required TO the airport (Y/N)?' => array('guest2_require_transportation_departure', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> Departure Date<br>(yyyy-mm-dd)<br>' => array('guest3_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('guest3_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('guest3_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest3_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('guest3_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> Transportation required TO the airport (Y/N)?' => array('guest3_require_transportation_departure', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> Departure Date<br>(yyyy-mm-dd)<br>' => array('guest4_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('guest4_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('guest4_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest4_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('guest4_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> Transportation required TO the airport (Y/N)?' => array('guest4_require_transportation_departure', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> Departure Date<br>(yyyy-mm-dd)<br>' => array('guest5_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('guest5_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('guest5_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest5_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('guest5_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> Transportation required TO the airport (Y/N)?' => array('guest5_require_transportation_departure', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> Departure Date<br>(yyyy-mm-dd)<br>' => array('guest6_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('guest6_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('guest6_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest6_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('guest6_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> Transportation required TO the airport (Y/N)?' => array('guest6_require_transportation_departure', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> Departure Date<br>(yyyy-mm-dd)<br>' => array('guest7_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('guest7_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('guest7_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest7_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('guest7_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> Transportation required TO the airport (Y/N)?' => array('guest7_require_transportation_departure', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> Departure Date<br>(yyyy-mm-dd)<br>' => array('guest8_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('guest8_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('guest8_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest8_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('guest8_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> Transportation required TO the airport (Y/N)?' => array('guest8_require_transportation_departure', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> Departure Date<br>(yyyy-mm-dd)<br>' => array('guest9_departure_date', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> Departure Time<br><span style="font-size: 11.004px; display:...' => array('guest9_departure_time', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => array('guest9_departure_flight', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important...' => array('guest9_departure_flight_number', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => array('guest9_departure_airport', 'varchar(30)'),
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> Transportation required TO the airport (Y/N)?' => array('guest9_require_transportation_departure', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('primary_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('primary_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('primary_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Approx. Departure Time <br>(hh:mm am/pm)' => array('primary_departure_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('guest1_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('guest1_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('guest1_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Approx. Departure Time <br>(hh:mm am/pm)' => array('guest1_departure_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('guest2_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('guest2_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('guest2_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Approx. Departure Time <br>(hh:mm am/pm)' => array('guest2_departure_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('guest3_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('guest3_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('guest3_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Approx. Departure Time <br>(hh:mm am/pm)' => array('guest3_departure_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('guest4_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('guest4_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('guest4_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Approx. Departure Time <br>(hh:mm am/pm)' => array('guest4_departure_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('guest5_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('guest5_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('guest5_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Approx. Departure Time <br>(hh:mm am/pm)' => array('guest5_departure_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('guest6_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('guest6_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('guest6_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Approx. Departure Time <br>(hh:mm am/pm)' => array('guest6_departure_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('guest7_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('guest7_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('guest7_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Approx. Departure Time <br>(hh:mm am/pm)' => array('guest7_departure_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('guest8_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('guest8_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('guest8_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Approx. Departure Time <br>(hh:mm am/pm)' => array('guest8_departure_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => array('guest9_arrival_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Approx. Arrival Time <br>(hh:mm am/pm)' => array('guest9_arrival_time_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Departure Date from Houston <br>(yyyy-mm-dd)' => array('guest9_departure_date_driving', 'varchar(30)'),
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Approx. Departure Time <br>(hh:mm am/pm)' => array('guest9_departure_time_driving', 'varchar(30)'),
    'LODGING/LIVING ARRANGEMENTS: Have you made hotel/lodging arrangements?' => array('hotel_arrangements', 'varchar(30)'),
    'Are all the people you are registering staying in the same hotel/accommodation?' => array('accomodation_same', 'varchar(30)'),
    'At which Hotel / Accommodations are you staying (please specify name and address)?' => array('hotel_detail_same', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> You (Primary Registrant) >> Hotel/Accommodation <br>(Name & Address)' => array('primary_hotel_detail', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 1 >> Hotel/Accommodation <br>(Name & Address)' => array('guest1_hotel_detail', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 2 >> Hotel/Accommodation <br>(Name & Address)' => array('guest2_hotel_detail', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 3 >> Hotel/Accommodation <br>(Name & Address)' => array('guest3_hotel_detail', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 4 >> Hotel/Accommodation <br>(Name & Address)' => array('guest4_hotel_detail', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 5 >> Hotel/Accommodation <br>(Name & Address)' => array('guest5_hotel_detail', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 6 >> Hotel/Accommodation <br>(Name & Address)' => array('guest6_hotel_detail', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 7 >> Hotel/Accommodation <br>(Name & Address)' => array('guest7_hotel_detail', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 8 >> Hotel/Accommodation <br>(Name & Address)' => array('guest8_hotel_detail', 'varchar(30)'),
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 9 >> Hotel/Accommodation <br>(Name & Address)' => array('guest9_hotel_detail', 'varchar(30)'),
    'GROUND TRANSPORTATION: How do you intend to get to/from the hotels and venues/events?' => array('ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> You (Primary Registrant) >> Transportation required from SNM Partner hotels <br>to/from ...' => array('primary_ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> Guest 1 >> Transportation required from SNM Partner hotels <br>to/from ...' => array('guest1_ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ...' => array('guest2_ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 2' => array('guest3_ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 3' => array('guest4_ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 4' => array('guest5_ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 5' => array('guest6_ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 6' => array('guest7_ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 7' => array('guest8_ground_transportation', 'varchar(30)'),
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 8' => array('guest9_ground_transportation', 'varchar(30)'),
    'OPTIONAL VOLUNTEER: If you or members of your group are part of the Sewadal or interested in Volunteering for this event, kindly select the skills/experience you already have, or have helped with previously (check all that apply). Please also take a moment to update your profile at http://nirankari.org/intranet/community so we know your skills for future sewa opportunities' => array('volunteer', 'varchar(30)'),
    'Medical Field: Area of Expertise' => array('medical', 'varchar(30)'),
    'State of License' => array('medical_state_of_license', 'varchar(30)'),
    'Do you want to submit a Poster?' => array('submit_poster', 'varchar(30)'),
    'Please enter a brief description about the poster(s).' => array('poster_description', 'varchar(30)'),
    'Are you bringing any medications/supplies/equipment?' => array('bringing_medical_equipment', 'varchar(30)'),
    'What type of medications/supplies/equipment?' => array('what_medical_equipment', 'varchar(30)'),
    'Legal Acknowledgement' => array('legal', 'varchar(30)'),
    'Unique ID (please note down this number)' => array('unique_id', 'varchar(30)')
);

?>

<!DOCTYPE html>
<html>
<head>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}

.blue { color:#0033cc;}
</style>
</head>
<body>


<?php

$table = '<table>
  <tr>
    <th>Column Name</th>
    <th>Jotform Caption</th>
  </tr>
';

$sql = "CREATE TABLE nss_registrations (
id INT(6) AUTO_INCREMENT PRIMARY KEY, ";

foreach ($excel_headers as $header => $columnArr) {
    $table .= '<tr>
    <td>'.$columnArr[0].'</td>
    <td>'.$header.'</td>
  </tr>
';
    
    $sql .= "$columnArr[0] $columnArr[1], ";
}

$table .= '</table>';

echo $table;

//echo $sql;
//echo "<pre>";
//print_r($excel_headers);
// OLD Headers

$excel_headers_old = array(
    'IP' => 'ip',
    'Submission ID' => 'submission_id',
    'Submission Date' => 'submission_date',
    'First Name' => 'first_name',
    'Last Name' => 'last_name',
    'Country of Residence' => 'country_of_residence',
    'SNM  Branch' => 'snm_branch',
    'E-mail' => 'email',
    'Mobile Phone Number' => 'phone',
    'Age (Guideline 7-30 yrs)' => 'age',
    'Gender' => 'gender',
    'T-Shirt Size' => 'tshirt_size',
    'Do you want to register Additional Guests?' => 'additional_guests',
    'Guest Name(s) and General Information >> Guest 1 >> First Name' => 'guest1_first_name',
    'Guest Name(s) and General Information >> Guest 1 >> Last Name' => 'guest1_last_name',
    'Guest Name(s) and General Information >> Guest 1 >> Gender <br>(M/F)' => 'guest1_gender',
    'Guest Name(s) and General Information >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest1_age',
    'Guest Name(s) and General Information >> Guest 1 >> Email <br>(leave blank <br>if no email)<br>' => 'guest1_email',
    'Guest Name(s) and General Information >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'guest1_phone',
    'Guest Name(s) and General Information >> Guest 2 >> First Name' => 'guest2_first_name',
    'Guest Name(s) and General Information >> Guest 2 >> Last Name' => 'guest2_last_name',
    'Guest Name(s) and General Information >> Guest 2 >> Gender <br>(M/F)' => 'guest2_gender',
    'Guest Name(s) and General Information >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest2_age',
    'Guest Name(s) and General Information >> Guest 2 >> Email <br>(leave blank <br>if no email)<br>' => 'guest2_email',
    'Guest Name(s) and General Information >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'guest2_phone',
    'Guest Name(s) and General Information >> Guest 3 >> First Name' => 'guest3_first_name',
    'Guest Name(s) and General Information >> Guest 3 >> Last Name' => 'guest3_last_name',
    'Guest Name(s) and General Information >> Guest 3 >> Gender <br>(M/F)' => 'guest3_gender',
    'Guest Name(s) and General Information >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest3_age',
    'Guest Name(s) and General Information >> Guest 3 >> Email <br>(leave blank <br>if no email)<br>' => 'guest3_email',
    'Guest Name(s) and General Information >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'guest3_phone',
    'Guest Name(s) and General Information >> Guest 4 >> First Name' => 'guest4_first_name',
    'Guest Name(s) and General Information >> Guest 4 >> Last Name' => 'guest4_last_name',
    'Guest Name(s) and General Information >> Guest 4 >> Gender <br>(M/F)' => 'guest4_gender',
    'Guest Name(s) and General Information >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest4_age',
    'Guest Name(s) and General Information >> Guest 4 >> Email <br>(leave blank <br>if no email)<br>' => 'guest4_email',
    'Guest Name(s) and General Information >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'guest4_phone',
    'Guest Name(s) and General Information >> Guest 5 >> First Name' => 'guest5_first_name',
    'Guest Name(s) and General Information >> Guest 5 >> Last Name' => 'guest5_last_name',
    'Guest Name(s) and General Information >> Guest 5 >> Gender <br>(M/F)' => 'guest5_gender',
    'Guest Name(s) and General Information >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest5_age',
    'Guest Name(s) and General Information >> Guest 5 >> Email <br>(leave blank <br>if no email)<br>' => 'guest5_email',
    'Guest Name(s) and General Information >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'guest5_phone',
    'Guest Name(s) and General Information >> Guest 6 >> First Name' => 'guest6_first_name',
    'Guest Name(s) and General Information >> Guest 6 >> Last Name' => 'guest6_last_name',
    'Guest Name(s) and General Information >> Guest 6 >> Gender <br>(M/F)' => 'guest6_gender',
    'Guest Name(s) and General Information >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest6_age',
    'Guest Name(s) and General Information >> Guest 6 >> Email <br>(leave blank <br>if no email)<br>' => 'guest6_email',
    'Guest Name(s) and General Information >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'guest6_phone',
    'Guest Name(s) and General Information >> Guest 7 >> First Name' => 'guest7_first_name',
    'Guest Name(s) and General Information >> Guest 7 >> Last Name' => 'guest7_last_name',
    'Guest Name(s) and General Information >> Guest 7 >> Gender <br>(M/F)' => 'guest7_gender',
    'Guest Name(s) and General Information >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest7_age',
    'Guest Name(s) and General Information >> Guest 7 >> Email <br>(leave blank <br>if no email)<br>' => 'guest7_email',
    'Guest Name(s) and General Information >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'guest7_phone',
    'Guest Name(s) and General Information >> Guest 8 >> First Name' => 'guest8_first_name',
    'Guest Name(s) and General Information >> Guest 8 >> Last Name' => 'guest8_last_name',
    'Guest Name(s) and General Information >> Guest 8 >> Gender <br>(M/F)' => 'guest8_gender',
    'Guest Name(s) and General Information >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest8_age',
    'Guest Name(s) and General Information >> Guest 8 >> Email <br>(leave blank <br>if no email)<br>' => 'guest8_email',
    'Guest Name(s) and General Information >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'guest8_phone',
    'Guest Name(s) and General Information >> Guest 9 >> First Name' => 'guest9_first_name',
    'Guest Name(s) and General Information >> Guest 9 >> Last Name' => 'guest9_last_name',
    'Guest Name(s) and General Information >> Guest 9 >> Gender <br>(M/F)' => 'guest9_gender',
    'Guest Name(s) and General Information >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest9_age',
    'Guest Name(s) and General Information >> Guest 9 >> Email <br>(leave blank <br>if no email)<br>' => 'guest9_email',
    'Guest Name(s) and General Information >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important... 2' => 'guest9_phone',
    'Guest T-Shirt Size >> Guest 1 >> Guest <br>T-shirt Size' => 'guest1_tshirt_size',
    'Guest T-Shirt Size >> Guest 2 >> Guest <br>T-shirt Size' => 'guest2_tshirt_size',
    'Guest T-Shirt Size >> Guest 3 >> Guest <br>T-shirt Size' => 'guest3_tshirt_size',
    'Guest T-Shirt Size >> Guest 4 >> Guest <br>T-shirt Size' => 'guest4_tshirt_size',
    'Guest T-Shirt Size >> Guest 5 >> Guest <br>T-shirt Size' => 'guest5_tshirt_size',
    'Guest T-Shirt Size >> Guest 6 >> Guest <br>T-shirt Size' => 'guest6_tshirt_size',
    'Guest T-Shirt Size >> Guest 7 >> Guest <br>T-shirt Size' => 'guest7_tshirt_size',
    'Guest T-Shirt Size >> Guest 8 >> Guest <br>T-shirt Size' => 'guest8_tshirt_size',
    'Guest T-Shirt Size >> Guest 9 >> Guest <br>T-shirt Size' => 'guest9_tshirt_size',
    'TRAVEL ARRANGEMENTS: Have you made travel arrangements / bookings to/from Houston?  (NOTE: all fields may not be visible if registering via mobile phone)' => 'travel_arrangements',
    'Is everyone you are registering traveling on the same itinerary (i.e. are you all traveling together)?' => 'same_guest_itinerary',
    'Date/Time of Arrival into Houston (please enter in time as well)' => 'arrival_time',
    'Arrival Flight Details' => 'arrival_flight',
    'Arrival Flight Number' => 'arrival_flight_number',
    'Arrival Airport?' => 'arrival_airport',
    'Do you require transportation FROM the Airport?' => 'require_transportation',
    'Date/Time of Departure from Houston (please enter in time as well)' => 'departure_time',
    'Departure Flight Details' => 'departure_flight',
    'Departure Flight Number' => 'departure_flight_number',
    'Departure Airport?' => 'departure_airport',
    'Do you (or everyone in your group) require transportation TO the Airport?' => 'require_transportation_all',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'primary_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'primary_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'primary_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> <span style="font-size: 11.004px; display: inline !important...' => 'primary_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'primary_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> You (Primary Registrant) >> Transportation required FROM the airport (Y/N)?' => 'primary_require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'guest1_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'guest1_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'guest1_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest1_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'guest1_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 1 >> Transportation required FROM the airport (Y/N)?' => 'guest1_require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'guest2_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'guest2_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'guest2_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest2_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'guest2_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 2 >> Transportation required FROM the airport (Y/N)?' => 'guest2_require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'guest3_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'guest3_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'guest3_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest3_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'guest3_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 3 >> Transportation required FROM the airport (Y/N)?' => 'guest3_require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'guest4_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'guest4_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'guest4_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest4_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'guest4_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 4 >> Transportation required FROM the airport (Y/N)?' => 'guest4_require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'guest5_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'guest5_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'guest5_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest5_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'guest5_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 5 >> Transportation required FROM the airport (Y/N)?' => 'guest5_require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'guest6_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'guest6_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'guest6_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest6_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'guest6_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 6 >> Transportation required FROM the airport (Y/N)?' => 'guest6_require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'guest7_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'guest7_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'guest7_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest7_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'guest7_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 7 >> Transportation required FROM the airport (Y/N)?' => 'guest7_require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'guest8_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'guest8_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'guest8_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest8_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'guest8_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 8 >> Transportation required FROM the airport (Y/N)?' => 'guest8_require_transportation_arrival',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> Arrival Date<br>(yyyy-mm-dd)<br>' => 'guest9_arrival_date',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> Arrival Time<br><span style="font-size: 11.004px; display: i...' => 'guest9_arrival_time',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> If Flying, Arriving Flight Carrier <br>(e.g. United)<br>' => 'guest9_arrival_flight',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest9_arrival_flight_number',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> If Flying, Arrival Airport <br>(IAH or HOU)<br>' => 'guest9_arrival_airport',
    'Flying Separately - Flight Arrival/Transportation Informatio... >> Guest 9 >> Transportation required FROM the airport (Y/N)?' => 'guest9_require_transportation_arrival',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> Departure Date<br>(yyyy-mm-dd)<br>' => 'primary_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'primary_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'primary_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> <span style="font-size: 11.004px; display: inline !important...' => 'primary_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'primary_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> You (Primary Registrant) >> Transportation required TO the airport (Y/N)?' => 'primary_require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'guest1_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'guest1_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'guest1_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest1_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'guest1_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 1 >> Transportation required TO the airport (Y/N)?' => 'guest1_require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'guest2_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'guest2_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'guest2_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest2_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'guest2_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 2 >> Transportation required TO the airport (Y/N)?' => 'guest2_require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'guest3_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'guest3_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'guest3_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest3_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'guest3_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 3 >> Transportation required TO the airport (Y/N)?' => 'guest3_require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'guest4_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'guest4_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'guest4_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest4_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'guest4_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 4 >> Transportation required TO the airport (Y/N)?' => 'guest4_require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'guest5_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'guest5_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'guest5_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest5_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'guest5_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 5 >> Transportation required TO the airport (Y/N)?' => 'guest5_require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'guest6_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'guest6_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'guest6_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest6_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'guest6_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 6 >> Transportation required TO the airport (Y/N)?' => 'guest6_require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'guest7_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'guest7_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'guest7_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest7_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'guest7_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 7 >> Transportation required TO the airport (Y/N)?' => 'guest7_require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'guest8_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'guest8_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'guest8_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest8_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'guest8_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 8 >> Transportation required TO the airport (Y/N)?' => 'guest8_require_transportation_departure',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> Departure Date<br>(yyyy-mm-dd)<br>' => 'guest9_departure_date',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> Departure Time<br><span style="font-size: 11.004px; display:...' => 'guest9_departure_time',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> If Flying, Departing Flight Carrier <br>(e.g. United)<br>' => 'guest9_departure_flight',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> <span style="font-size: 11.004px; display: inline !important...' => 'guest9_departure_flight_number',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> If Flying, Departure Airport <br>(IAH or HOU)<br>' => 'guest9_departure_airport',
    'Flying Separately - Flight Departure/Transportation Informat... >> Guest 9 >> Transportation required TO the airport (Y/N)?' => 'guest9_require_transportation_departure',
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'primary_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'primary_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'primary_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> You (Primary Registrant) >> Approx. Departure Time <br>(hh:mm am/pm)' => 'primary_departure_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'guest1_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'guest1_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'guest1_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 1 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'guest1_departure_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'guest2_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'guest2_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'guest2_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 2 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'guest2_departure_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'guest3_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'guest3_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'guest3_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 3 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'guest3_departure_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'guest4_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'guest4_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'guest4_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 4 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'guest4_departure_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'guest5_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'guest5_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'guest5_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 5 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'guest5_departure_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'guest6_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'guest6_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'guest6_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 6 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'guest6_departure_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'guest7_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'guest7_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'guest7_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 7 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'guest7_departure_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'guest8_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'guest8_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'guest8_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 8 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'guest8_departure_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Arrival Date into Houston <br>(yyyy-mm-dd)' => 'guest9_arrival_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Approx. Arrival Time <br>(hh:mm am/pm)' => 'guest9_arrival_time_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Departure Date from Houston <br>(yyyy-mm-dd)' => 'guest9_departure_date_driving',
    'Driving Separately - Arrival & Departure Information >> Guest 9 >> Approx. Departure Time <br>(hh:mm am/pm)' => 'guest9_departure_time_driving',
    'LODGING/LIVING ARRANGEMENTS: Have you made hotel/lodging arrangements?' => 'hotel_arrangements',
    'Are all the people you are registering staying in the same hotel/accommodation?' => 'accomodation_same',
    'At which Hotel / Accommodations are you staying (please specify name and address)?' => 'hotel_detail_same',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> You (Primary Registrant) >> Hotel/Accommodation <br>(Name & Address)' => 'primary_hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 1 >> Hotel/Accommodation <br>(Name & Address)' => 'guest1_hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 2 >> Hotel/Accommodation <br>(Name & Address)' => 'guest2_hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 3 >> Hotel/Accommodation <br>(Name & Address)' => 'guest3_hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 4 >> Hotel/Accommodation <br>(Name & Address)' => 'guest4_hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 5 >> Hotel/Accommodation <br>(Name & Address)' => 'guest5_hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 6 >> Hotel/Accommodation <br>(Name & Address)' => 'guest6_hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 7 >> Hotel/Accommodation <br>(Name & Address)' => 'guest7_hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 8 >> Hotel/Accommodation <br>(Name & Address)' => 'guest8_hotel_detail',
    'Separate Hotels/Accommodations - At which Hotel are you stay... >> Guest 9 >> Hotel/Accommodation <br>(Name & Address)' => 'guest9_hotel_detail',
    'GROUND TRANSPORTATION: How do you intend to get to/from the hotels and venues/events?' => 'ground_transportation',
    'Individual Ground Transportation Details >> You (Primary Registrant) >> Transportation required from SNM Partner hotels <br>to/from ...' => 'primary_ground_transportation',
    'Individual Ground Transportation Details >> Guest 1 >> Transportation required from SNM Partner hotels <br>to/from ...' => 'guest1_ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ...' => 'guest2_ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 2' => 'guest3_ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 3' => 'guest4_ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 4' => 'guest5_ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 5' => 'guest6_ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 6' => 'guest7_ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 7' => 'guest8_ground_transportation',
    'Individual Ground Transportation Details >> <span style="font-size: 11.004px; display: inline !important... >> Transportation required from SNM Partner hotels <br>to/from ... 8' => 'guest9_ground_transportation',
    'OPTIONAL VOLUNTEER: If you or members of your group are part of the Sewadal or interested in Volunteering for this event, kindly select the skills/experience you already have, or have helped with previously (check all that apply). Please also take a moment to update your profile at http://nirankari.org/intranet/community so we know your skills for future sewa opportunities' => 'volunteer',
    'Medical Field: Area of Expertise' => 'medical',
    'State of License' => 'medical_state_of_license',
    'Do you want to submit a Poster?' => 'submit_poster',
    'Please enter a brief description about the poster(s).' => 'poster_description',
    'Are you bringing any medications/supplies/equipment?' => 'bringing_medical_equipment',
    'What type of medications/supplies/equipment?' => 'what_medical_equipment',
    'Legal Acknowledgement' => 'legal',
    'Unique ID (please note down this number)' => 'unique_id'
);
?>